config/routes.rb
WebsiteFrancisFerrari::Application.routes.draw do
  resources :nifty_corners

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
  scope do
    match "contents/:uuid/backgrounds" => "backgrounds#index", :via => "GET"
    match "annoncments/:title_annoncment_id/backgrounds" => "backgrounds#index", :via => "GET"
    match "contents/:uuid" => "contents#show", :via => "GET"
  end

  resources :personalize_galery_photo_backgrounds
  resources :searchs do
    get :link_load_form_search, :on => :collection
  end
  resources :localisation_shops do
    get :localisation_shops_list, on: :collection
  end
  resources :categories_sub_menus_galery_photos
  resources :categories_sub_menus_annoncments
  resources :categories_sub_menus
  resources :title_websites
  resources :languages, :only => :show
  resources :contact_us
  resources :personalize_backgrounds
  resources :header_backgrounds
  resources :footer_backgrounds
  resources :sub_menu_backgrounds
  resources :background_by_defaults
  resources :menu_backgrounds
  resources :footers
  resources :categories, :as => "title" do
    resources :submenus, :as => "title_submenu" do
      resources :galery_photos
      resources :contents, :as => "uuid" do
        resources :backgrounds
      end
      resources :annoncments, :as => "title_annoncment" do
        resources :backgrounds
        resources :photos
      end
    end
    resources :galery_photos
    resources :contents
    resources :annoncments do
      resources :photos
    end
  end

  root :to => "home#index"

  namespace :admin do
    resources :personalize_galery_photo_backgrounds do
      post :activation, :on => :collection
    end
    resources :localisation_shops do
      post :import_localisation_shops, on: :collection
    end
    resources :title_websites
    resources :robot_keys
    resources :personalize_backgrounds do
      post :activation, :on => :collection
    end
    resources :contact_us
    resources :footers
    resources :sub_menu_backgrounds do
      post :activation, :on => :collection
    end
    resources :menu_backgrounds do
      post :activation, :on => :collection
      get :get_activation, :on => :collection
    end
    resources :footer_backgrounds do
      post :activation, :on => :collection
    end
    resources :header_backgrounds do
      post :activation, :on => :collection
    end
    resources :background_by_defaults do
      post :activation, :on => :collection
    end
    scope do 
      match "categories/annoncments/sort" => "annoncments#sort", :via => "GET"
    end
    resources :categories, :as => "title" do
      scope do
        match "submenus/:title_submenu_id/update_success" => "submenus#update_success", :via => "GET"
        match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
      end
      resources :submenus, :as => "title_submenu" do
        get :sort, :on => :collection
        post :content_or_annoncment_homepage, :on => :collection
        get :update_success, :on => :member
        resources :galery_photos
        scope do
          match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
        end
        resources :contents do
          get :copy, :on => :collection
          get :sort, :on => :collection
        end
        resources :annoncments do
          get :sort, :on => :collection
          resources :photos do
            get :add_form_photo, :on => :collection
          end
        end
      end 
      resources :galery_photos
      resources :contents do
        get :sort, :on => :collection
      end
      get :sort, :on => :collection
      post :homepage, :on => :collection
      scope do
        match "photos/add_form_photo" => "photos#add_form_photo", :via => "GET"
      end
      resources :annoncments do
        get :sort, :on => :collection
        resources :photos do
          get :add_form_photo, :on => :collection
        end
      end
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessor :drop_photo
  before_save :generate_uuid
  belongs_to :annoncment

  mount_uploader :photo, PhotoUploader

  scope :position, ->(index, id) { update_all(['position=?', index], ['id=?', id]) }
  
  accepts_nested_attributes_for :annoncment

  def generate_uuid
    uuid = UUID.new
    self.uuid = uuid.generate
  end
end

app/controllers/admin/photos_controller.rb
module Admin
  class PhotosController < AdminController
    before_action :set_photo, only: [:show, :edit, :update, :destroy]
    before_action :load_category_by_title, except: [:add_form_photo]
    before_action :load_annoncment_by_titl, except: [:add_form_photo]

    def index
      @photos = @annoncment.photos
    end

    def new
      @photo = @annoncment.photos.new
    end

    def edit
    end

    def create
      @photo = @annoncment.photos.new(photo_params)

      if @photo.save
        redirect_to admin_title_annoncment_photos_path(@category.title, @annoncment.title, notice: "Photo was successfully created")
      else
        render action: 'new'
      end
    end

    def update
      if @photo.update(photo_params)
        redirect_to admin_title_annoncment_photos_path(@category.title, @annoncment.title, notice: "Photo cas successfully updated")
      else
        render action: 'edit'
      end
    end

    def destroy
      @photo.destroy
      redirect_to edit_admin_title_annoncment_path(@category.title, @annoncment.title)
    end

    def add_form_photo
      respond_to do |format|
        format.js
      end
    end

    private 
      def set_photo
        @photo = Photo.find_by_uuid(params[:id]) 
      end

      def load_annoncment_by_title
        @annoncment = load_category_by_title.annoncments.find_by_title(params[:id])
      end

      def photo_params
        params.require(:photo).permit(:id,
                                      :photo,
                                      :photo_cache,
                                      :annoncment_id,
                                      :master_image,
                                      :uuid
                                     )
      end
  end
end

app/views/admin/photos/templates/_form_fields_edit_record_photos.html.slim
- @annoncment.photos.each do |photo|
  = f.fields_for(:photos, photo) do |f_photo|
    .row
      .col-md-12.annoncment_photos
        = render(:partial => "/admin/photos/templates/form_input_photos", :locals => { f_photo: f_photo , photo: photo })

app/views/admin/photos/templates/_form_fields_new_record_photos.html.slim
= f.fields_for(:photos, @annoncment.photos.new) do |f_photo|
    .row
      .col-md-5.annoncment_photos
        = render(:partial => "/admin/photos/templates/form_input_photos", :locals => { f_photo: f_photo})

app/views/admin/photos/templates/_form_input_photos.html.slim
.row
  - if @annoncment.new_record? || @annoncment.photos.empty?
    .col-md-6
      = f_photo.input :uuid, as: :hidden
      = f_photo.input :photo
  - else
    .col-md-3
      = f_photo.input :uuid, as: :hidden
      = f_photo.input :photo
  - unless @annoncment.new_record? || @annoncment.photos.empty?
    .col-md-3
      .row
        = t(".show_photo")
      .row
         = image_tag(photo.photo.url(:thumb))
      .col-md-3
        = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_title_annoncment_photo_path(@category.title, @annoncment.title, photo.uuid), :confirm => t("admin.common.confirm_delete"), :method => :delete, :class => "btn btn-mini btn-danger"
    .col-md-3
      = render(:partial => "/admin/photos/templates/form_photo_master")
  - else
    .col-md-6
      = render(:partial => "/admin/photos/templates/form_photo_master")

app/views/admin/photos/templates/_form_photo_master.html.slim
.row
  = t(".image_master")
.row
  = radio_button 'annoncment[photos_master][master_image]', "", 0, :checked => true