config/routes.rb
WebsiteFrancisFerrari::Application.routes.draw do
  resources :nifty_corners

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
  scope do
    match "contents/:uuid/backgrounds" => "backgrounds#index", :via => "GET"
    match "annoncments/:title_annoncment_id/backgrounds" => "backgrounds#index", :via => "GET"
    match "contents/:uuid" => "contents#show", :via => "GET"
  end

  resources :personalize_galery_photo_backgrounds
  resources :searchs do
    get :link_load_form_search, :on => :collection
  end
  resources :localisation_shops do
    get :localisation_shops_list, on: :collection
  end
  resources :categories_sub_menus_galery_photos
  resources :categories_sub_menus_annoncments
  resources :categories_sub_menus
  resources :title_websites
  resources :languages, :only => :show
  resources :contact_us
  resources :personalize_backgrounds
  resources :header_backgrounds
  resources :footer_backgrounds
  resources :sub_menu_backgrounds
  resources :background_by_defaults
  resources :menu_backgrounds
  resources :footers
  resources :categories, :as => "title" do
    resources :submenus, :as => "title_submenu" do
      resources :galery_photos
      resources :contents, :as => "uuid" do
        resources :backgrounds
      end
      resources :annoncments, :as => "title_annoncment" do
        resources :backgrounds
        resources :photos
      end
    end
    resources :galery_photos
    resources :contents
    resources :annoncments do
      resources :photos
    end
  end

  root :to => "home#index"

  namespace :admin do
    resources :personalize_galery_photo_backgrounds do
      post :activation, :on => :collection
    end
    resources :localisation_shops do
      post :import_localisation_shops, on: :collection
    end
    resources :title_websites
    resources :robot_keys
    resources :personalize_backgrounds do
      post :activation, :on => :collection
    end
    resources :contact_us
    resources :footers
    resources :sub_menu_backgrounds do
      post :activation, :on => :collection
    end
    resources :menu_backgrounds do
      post :activation, :on => :collection
      get :get_activation, :on => :collection
    end
    resources :footer_backgrounds do
      post :activation, :on => :collection
    end
    resources :header_backgrounds do
      post :activation, :on => :collection
    end
    resources :background_by_defaults do
      post :activation, :on => :collection
    end
    scope do 
      match "categories/annoncments/sort" => "annoncments#sort", :via => "GET"
    end
    resources :categories, :as => "title" do
      scope do
        match "submenus/:title_submenu_id/update_success" => "submenus#update_success", :via => "GET"
        match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
      end
      resources :submenus, :as => "title_submenu" do
        get :sort, :on => :collection
        post :content_or_annoncment_homepage, :on => :collection
        get :update_success, :on => :member
        resources :galery_photos
        scope do
          match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
        end
        resources :contents do
          get :copy, :on => :collection
          get :sort, :on => :collection
        end
        resources :annoncments do
          get :sort, :on => :collection
          resources :photos do
            get :add_form_photo, :on => :collection
          end
        end
      end 
      resources :galery_photos
      resources :contents do
        get :sort, :on => :collection
      end
      get :sort, :on => :collection
      post :homepage, :on => :collection
      scope do
        match "photos/add_form_photo" => "photos#add_form_photo", :via => "GET"
      end
      resources :annoncments do
        get :sort, :on => :collection
        resources :photos do
          get :add_form_photo, :on => :collection
        end
      end
    end
  end

end

app/models/sub_menu_background.rb
class SubMenuBackground < ActiveRecord::Base
  validates_presence_of :title
  before_save :generate_uuid
  has_one :font, as: :fontstyles, dependent: :destroy
  has_one :background, as: :backgroundstyles, dependent: :destroy 
  has_one :align, as: :aligns, dependent: :destroy
  has_one :click_link, as: :click_linkstyles, dependent: :destroy
  before_save :set_activation_by_default?
  accepts_nested_attributes_for :background,
                                :allow_destroy => true
  accepts_nested_attributes_for :align
  accepts_nested_attributes_for :click_link,
                                :allow_destroy => true

  accepts_nested_attributes_for :font,
                                :allow_destroy => true

  def self.activation!(activation)
    hash_activation = Hash.new
    background_by_default_id = activation.first
    hash_activation[:activation] = true
    sub_menu_background = SubMenuBackground.find(background_by_default_id)
    return sub_menu_background.activation == false ? sub_menu_background.update(hash_activation) : sub_menu_background
  end

  def generate_uuid
    uuid = UUID.new
    self.uuid = uuid.generate
  end

  private
  def set_activation_by_default?
    if self.id
      sub_menu_background = SubMenuBackground.find(self.id)
      set_activation_by_default if self.activation == true && sub_menu_background.activation == false
    else
      set_activation_by_default
    end
  end

  def set_activation_by_default
    SubMenuBackground.update_all(:activation => false)
  end
end

app/controllers/admin/sub_menu_backgrounds_controller.rb
module Admin
  class SubMenuBackgroundsController < AdminController
    before_action :set_sub_menu_background, only: [:show, :edit, :update, :destroy]

    def index
      @sub_menu_backgrounds = SubMenuBackground.all
    end

    def show
      respond_to do |format|
        format.html
        format.json { render json: @sub_menu_background.to_json(:include => [:background, :align]) }
      end
    end

    def new
      @sub_menu_background = SubMenuBackground.new
    end

    def edit
    end

    def create
      @sub_menu_background = SubMenuBackground.new(sub_menu_background_params)
      
      if @sub_menu_background.save
        redirect_to admin_sub_menu_backgrounds_path, notice: t(".sub_menu_background_success_created")
      else
        render action: 'new'
      end
    end

    def update
      if @sub_menu_background.update(sub_menu_background_params)
        redirect_to admin_sub_menu_backgrounds_path, notice: t(".sub_menu_background_success_updated")
      else
        render action: 'edit'
      end
    end

    def destroy
      notice = @sub_menu_background.destroy ? t(".sub_menu_background_success_deleted") : t(".sub_menu_background_not_success_deleted")
      redirect_to admin_sub_menu_backgrounds_path, notice: notice 
    end

    def activation
      notice = SubMenuBackground.activation!(params[:sub_menu_background][:activation]) ? t(".sub_menu_background_success_defined") : t(".sub_menu_background_not_success_defined")
      redirect_to admin_sub_menu_backgrounds_path, notice: notice
    end

    private
    def set_sub_menu_background
      @sub_menu_background = SubMenuBackground.find_by_uuid(params[:id])
    end

    def sub_menu_background_params
      params.require(:sub_menu_background).permit(:id,
                                                  :title,
                                                  :activation,
                                                  activation: [],
                                                  align_attributes: [:align, :id],
                                                  font_attributes: [:font_family, :font_size, :id],
                                                  background_attributes: [:border, :border_style, :background_color, :delete_background_image, :no_background_image, :background_image, :cached_path, :no_repeat, :border_color, :background_image_size, :cover, :opacity, :transparent, :id],
                                                  click_link_attributes: [:color, :background_color, :id]
                                                 )
    end
  end
end

app/controllers/sub_menu_backgrounds_controller.rb
class SubMenuBackgroundsController < ApplicationController
  before_action :set_sub_menu_background, only: [:show, :edit, :update, :destroy]

  # GET /sub_menu_backgrounds
  # GET /sub_menu_backgrounds.json
  def index
    @sub_menu_background = SubMenuBackground.find_by_activation(true)

    respond_to do |format|
      format.html
      format.json { render json: @sub_menu_background.to_json(:include => [:background, :click_link, :font]) }
    end
  end

  # GET /sub_menu_backgrounds/1
  # GET /sub_menu_backgrounds/1.json
  def show
  end

  # GET /sub_menu_backgrounds/new
  def new
    @sub_menu_background = SubMenuBackground.new
  end

  # GET /sub_menu_backgrounds/1/edit
  def edit
  end

  # POST /sub_menu_backgrounds
  # POST /sub_menu_backgrounds.json
  def create
    @sub_menu_background = SubMenuBackground.new(sub_menu_background_params)

    respond_to do |format|
      if @sub_menu_background.save
        format.html { redirect_to @sub_menu_background, notice: 'Sub menu background was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sub_menu_background }
      else
        format.html { render action: 'new' }
        format.json { render json: @sub_menu_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_menu_backgrounds/1
  # PATCH/PUT /sub_menu_backgrounds/1.json
  def update
    respond_to do |format|
      if @sub_menu_background.update(sub_menu_background_params)
        format.html { redirect_to @sub_menu_background, notice: 'Sub menu background was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sub_menu_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_menu_backgrounds/1
  # DELETE /sub_menu_backgrounds/1.json
  def destroy
    @sub_menu_background.destroy
    respond_to do |format|
      format.html { redirect_to sub_menu_backgrounds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_menu_background
      @sub_menu_background = SubMenuBackground.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_menu_background_params
      params[:sub_menu_background]
    end
end

app/helpers/sub_menu_backgrounds_helper.rb
module SubMenuBackgroundsHelper
end

app/views/admin/sub_menu_backgrounds/_form.html.slim
= simple_form_for [:admin, @sub_menu_background], url: url do |f|
  = f.input :title
  = f.input :activation 
  = render(partial: "/admin/fonts/form", locals: { f: f, model_init: @sub_menu_background.new_record? || @sub_menu_background.font.nil? ? Font.new : @sub_menu_background.font, model: @sub_menu_background })
  = render(:partial => "/admin/aligns/form", :locals => { f: f, model_init: @sub_menu_background.new_record? || @sub_menu_background.align.nil? ? Align.new : @sub_menu_background.align, model: @sub_menu_background })
  = render(:partial => "/admin/backgrounds/background", :locals => { f: f, model_init: @sub_menu_background.new_record? || @sub_menu_background.background.nil? ? Background.new : @sub_menu_background.background, model: @sub_menu_background }) 
  = render(:partial => "/admin/click_links/form", :locals => { f: f, model_init: @sub_menu_background.new_record? || @sub_menu_background.background.nil? ? ClickLink.new : @sub_menu_background.click_link, model: @sub_menu_background})
  .form-actions
    = f.button :submit, value: button_valid_sub_menu_background, :class => 'btn-primary'

app/views/admin/sub_menu_backgrounds/edit.html.slim
= render(:partial => "/admin/sub_menu_backgrounds/form", locals: {button_valid_sub_menu_background: t(".button.valid_edit_sub_menu_background"), url: admin_sub_menu_background_path(@sub_menu_background.uuid) })

app/views/admin/sub_menu_backgrounds/index.html.slim
- model_class = SubMenuBackground

.page-header
  h1
    = t(".title")

= form_tag :action => 'activation', :controller => "sub_menu_backgrounds"
  table.table.table-striped
    tr
      th.col-md-4= model_class.human_attribute_name(:title)
      th.col-md-4= model_class.human_attribute_name(:activation)
      th.col-md-4= t '.actions', :default => t("helpers.actions")
    - @sub_menu_backgrounds.each do |sub_menu_background|
      tr.tr_content_common
        td.col-md-4
          = sub_menu_background.title
        td.col-md-4
          = radio_button "sub_menu_background[activation]", "", sub_menu_background.id, checked: sub_menu_background.activation
        td.col-md-4
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_sub_menu_background_path(sub_menu_background.uuid), class: 'btn btn-mini btn-primary'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_sub_menu_background_path(sub_menu_background.uuid), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("admin.common.confirm_delete"))) }, :class => 'btn btn-mini btn-danger'
  
  .row
    .col-md-10
      = link_to t(".new", :default => t("helpers.links.new")), new_admin_sub_menu_background_path, class: 'btn btn-primary'
    .col-md-2
      = submit_tag t("admin.common.valid"), name: "activation_sub_menu_backgrounds_activate", class: "btn btn-success"

app/views/admin/sub_menu_backgrounds/new.html.slim
= render(:partial => "/admin/sub_menu_backgrounds/form", :locals => {button_valid_sub_menu_background: t(".button.valid_new_sub_menu_background"), :url => admin_sub_menu_backgrounds_path })

app/views/admin/sub_menu_backgrounds/show.html.slim
- model_class = SubMenuBackground

.page-header
  .row
    .col-md-2
      h1= t '.title', default: model_class.model_name.human.titleize
    .col-md-10
      .pull-right
        .btn-toolbar
          .btn-toolbar
            .btn-group

.row.sub_menu_background