config/routes.rb
WebsiteFrancisFerrari::Application.routes.draw do
  resources :nifty_corners

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
  scope do
    match "contents/:uuid/backgrounds" => "backgrounds#index", :via => "GET"
    match "annoncments/:title_annoncment_id/backgrounds" => "backgrounds#index", :via => "GET"
    match "contents/:uuid" => "contents#show", :via => "GET"
  end

  resources :personalize_galery_photo_backgrounds
  resources :searchs do
    get :link_load_form_search, :on => :collection
  end
  resources :localisation_shops do
    get :localisation_shops_list, on: :collection
  end
  resources :categories_sub_menus_galery_photos
  resources :categories_sub_menus_annoncments
  resources :categories_sub_menus
  resources :title_websites
  resources :languages, :only => :show
  resources :contact_us
  resources :personalize_backgrounds
  resources :header_backgrounds
  resources :footer_backgrounds
  resources :sub_menu_backgrounds
  resources :background_by_defaults
  resources :menu_backgrounds
  resources :footers
  resources :categories, :as => "title" do
    resources :submenus, :as => "title_submenu" do
      resources :galery_photos
      resources :contents, :as => "uuid" do
        resources :backgrounds
      end
      resources :annoncments, :as => "title_annoncment" do
        resources :backgrounds
        resources :photos
      end
    end
    resources :galery_photos
    resources :contents
    resources :annoncments do
      resources :photos
    end
  end

  root :to => "home#index"

  namespace :admin do
    resources :personalize_galery_photo_backgrounds do
      post :activation, :on => :collection
    end
    resources :localisation_shops do
      post :import_localisation_shops, on: :collection
    end
    resources :title_websites
    resources :robot_keys
    resources :personalize_backgrounds do
      post :activation, :on => :collection
    end
    resources :contact_us
    resources :footers
    resources :sub_menu_backgrounds do
      post :activation, :on => :collection
    end
    resources :menu_backgrounds do
      post :activation, :on => :collection
      get :get_activation, :on => :collection
    end
    resources :footer_backgrounds do
      post :activation, :on => :collection
    end
    resources :header_backgrounds do
      post :activation, :on => :collection
    end
    resources :background_by_defaults do
      post :activation, :on => :collection
    end
    scope do 
      match "categories/annoncments/sort" => "annoncments#sort", :via => "GET"
    end
    resources :categories, :as => "title" do
      scope do
        match "submenus/:title_submenu_id/update_success" => "submenus#update_success", :via => "GET"
        match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
      end
      resources :submenus, :as => "title_submenu" do
        get :sort, :on => :collection
        post :content_or_annoncment_homepage, :on => :collection
        get :update_success, :on => :member
        resources :galery_photos
        scope do
          match "contents/:content_uuid_for_copy/copy" => "contents#copy", :via => "GET"
        end
        resources :contents do
          get :copy, :on => :collection
          get :sort, :on => :collection
        end
        resources :annoncments do
          get :sort, :on => :collection
          resources :photos do
            get :add_form_photo, :on => :collection
          end
        end
      end 
      resources :galery_photos
      resources :contents do
        get :sort, :on => :collection
      end
      get :sort, :on => :collection
      post :homepage, :on => :collection
      scope do
        match "photos/add_form_photo" => "photos#add_form_photo", :via => "GET"
      end
      resources :annoncments do
        get :sort, :on => :collection
        resources :photos do
          get :add_form_photo, :on => :collection
        end
      end
    end
  end

end

app/models/personalize_galery_photo_background.rb
class PersonalizeGaleryPhotoBackground < ActiveRecord::Base
  validates_presence_of :title
  before_save :generate_uuid
  has_one :background, as: :backgroundstyles, dependent: :destroy
  before_save :set_activation_by_default?
  before_update :set_activation_by_default?
  accepts_nested_attributes_for :background,
                                :allow_destroy => true

  def self.activation!(activation)
    hash_activation = Hash.new
    personalize_galery_photo_background_id = activation.first
    hash_activation[:activation] = true
    personalize_galery_photo_background = PersonalizeGaleryPhotoBackground.find(personalize_galery_photo_background_id)
    return personalize_galery_photo_background.activation == false ? personalize_galery_photo_background.update(hash_activation) : personalize_galery_photo_background
  end

  def generate_uuid
    uuid = UUID.new
    self.uuid = uuid.generate
  end

  private
  def set_activation_by_default?
    if self.id
      personalize_galery_photo_background = PersonalizeGaleryPhotoBackground.find(self.id)
      set_activation_by_default if self.activation == true && personalize_galery_photo_background.activation == false
    else
      set_activation_by_default
    end
  end

  def set_activation_by_default
    PersonalizeGaleryPhotoBackground.update_all(activation: false)
  end
end

app/controllers/admin/personalize_galery_photo_backgrounds_controller.rb
module Admin
  class PersonalizeGaleryPhotoBackgroundsController < AdminController
    before_action :set_personalize_galery_photo_background, only: [:show, :edit, :update, :destroy]

    def index
      @personalize_galery_photo_backgrounds = PersonalizeGaleryPhotoBackground.all
    end

    def show

    end

    def new
      @personalize_galery_photo_background = PersonalizeGaleryPhotoBackground.new
    end

    def edit
    end

    def create
      @personalize_galery_photo_background = PersonalizeGaleryPhotoBackground.new(personalize_galery_photo_background_params)

      if @personalize_galery_photo_background.save
        redirect_to admin_personalize_galery_photo_backgrounds_path, notice: "La personalisation de l'arrière plan pour la galerie photo s'est bien déroulé, elle est désormais disponible"
      else
        render action: 'new'
      end
    end

    def update
      if @personalize_galery_photo_background.update(personalize_galery_photo_background_params)
        redirect_to admin_personalize_galery_photo_backgrounds_path, notice: "La mise à jour de l'arrière plan pour la galerie photo s'est bien déroulé, elle est désormais disponible"
      else
        render action: 'edit'
      end
    end

    def destroy
      notice = @personalize_galery_photo_background.destroy ? "La personalisation se l'arrière plan pour la galerie photo à bien été supprimé" : "La personalisation de l'arrière plan pour la galerie photo n'a pas été correctement supprimé"
      redirect_to admin_personalize_galery_photo_backgrounds_path, notice: notice
    end

    def activation
      notice = PersonalizeGaleryPhotoBackground.activation!(params[:personalize_galery_photo_background][:activations]) ? "L'activation de cette arrière plan pour la galerie d'image s'est bien déroulé, il est désormais disponible" : "L'activation de cette arrière plan pour la galerie d'image ne s'est pas déroulé correctement, il n'est pas disponible" 
      redirect_to admin_personalize_galery_photo_backgrounds_path, notice: notice
    end

    private
      def set_personalize_galery_photo_background
        @personalize_galery_photo_background = PersonalizeGaleryPhotoBackground.find_by_uuid(params[:id])
      end

      def personalize_galery_photo_background_params
        params.require(:personalize_galery_photo_background).permit(:id,
                                                                    :uuid,
                                                                    :title,
                                                                    :activation,
                                                                    activations: [],
                                                                    background_attributes: [:border, :border_style, :background_color, :delete_background_image, :no_background_image, :background_image, :cached_path, :no_repeat, :border_color, :align, :background_image_size, :cover, :opacity, :transparent, :id]
                                                                   )
      end 

  end
end

app/controllers/personalize_galery_photo_backgrounds_controller.rb
class PersonalizeGaleryPhotoBackgroundsController < ApplicationController
  before_action :set_personalize_galery_photo_background, only: [:show, :edit, :update, :destroy]

  def index
    @personalize_galery_photo_backgrounds = PersonalizeGaleryPhotoBackground.find_by_activation(true)
    respond_to do |format|
      format.json { render json: @personalize_galery_photo_backgrounds.to_json(:include => :background) }
    end
  end
end

app/views/admin/personalize_galery_photo_backgrounds/_form.html.slim
= simple_form_for [:admin, @personalize_galery_photo_background], url: url do |f|
  = f.input :title
  = f.input :activation
  = render(partial: "/admin/backgrounds/background", locals: { f: f, model_init: @personalize_galery_photo_background.new_record? || @personalize_galery_photo_background.background.nil? ? Background.new : @personalize_galery_photo_background.background, model: @personalize_galery_photo_background })
  .form-actions
    = f.button :submit, value: "Enregistrer", class: 'btn-primary'

app/views/admin/personalize_galery_photo_backgrounds/edit.html.slim
= render(:partial => "/admin/personalize_galery_photo_backgrounds/form", :locals => {button_valid_footer_background: t(".button.valid_new_footer_background"), :url => admin_personalize_galery_photo_background_path(@personalize_galery_photo_background.uuid) })

app/views/admin/personalize_galery_photo_backgrounds/index.html.slim
- model_class = PersonalizeGaleryPhotoBackground
.page-header
  h1 = t(".title")

= form_tag action: 'activation', controller: "personalize_galery_photo_backgrounds"
  table.table.table-striped
    thead
      tr
        th.col-md-4= model_class.human_attribute_name(:title)
        th.col-md-4= model_class.human_attribute_name(:activation)
        th.col-md-4= t '.actions', default: t("helpers.actions")
    tbody
      - @personalize_galery_photo_backgrounds.each do |personalize_galery_photo_background|
        tr
          td.col-md-4= personalize_galery_photo_background.title
          td.col-md-4= radio_button "personalize_galery_photo_background[activations]", "", personalize_galery_photo_background.id, checked: personalize_galery_photo_background.activation
          td.col-md-4
            = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_personalize_galery_photo_background_path(personalize_galery_photo_background.uuid), class: 'btn btn-mini btn-primary'
            '
            = link_to t('.destroy', default: t("helpers.links.destroy")), admin_personalize_galery_photo_background_path(personalize_galery_photo_background.uuid), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t("admin.common.confirm_delete"))) }, :class => 'btn btn-mini btn-danger'

  .row
    .col-md-10
      = link_to t(".new", default: t("helpers.links.new")), new_admin_personalize_galery_photo_background_path, class: 'btn btn-primary'
    .col-md-2
      = submit_tag t("admin.common.valid"), name: "activation_footer_background_activate", class: "btn btn-success"

app/views/admin/personalize_galery_photo_backgrounds/new.html.slim
= render(:partial => "/admin/personalize_galery_photo_backgrounds/form", :locals => {button_valid_footer_background: t(".button.valid_new_footer_background"), :url => admin_personalize_galery_photo_backgrounds_path })